name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: semantic version
      uses: paulhatch/semantic-version@v5.3.0
      with:
        tag_prefix: "v"
        major_pattern: "Major"
        minor_pattern: "Minor"
        patch_pattern: "Patch"
        version_format: "${major}.${minor}.${patch}"
        change_path: "frontend/"
        namespace: main
        search_commit_body: true
    - name: Push tag to origin
      run:  |
        git tag -a v${{ steps.semantic version.outputs.version }} -m "Version ${{ steps.semantic version.outputs.version }}"
        git push origin v${{ steps.semantic version.outputs.version }}

        
